services:
  db:
    image: pgvector/pgvector:pg16
    container_name: cassini_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cassini
      POSTGRES_PASSWORD: cassini
      POSTGRES_DB: cassini
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
